package IGU;

import Logica.Sistema;
import Logica.Vuelo;
import javax.swing.JOptionPane;

/**
 *
 * @author thoma
 */
public class Añadir extends javax.swing.JFrame {
    private Sistema sis;
    public Añadir(Sistema sistema) {      
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
             java.util.logging.Logger.getLogger(Añadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        this.sis = sistema;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Añadir = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jtxtFieldHrLleg = new javax.swing.JTextField();
        tltHrLleg = new javax.swing.JLabel();
        jtxtFieldHrParti = new javax.swing.JTextField();
        tltHrParti = new javax.swing.JLabel();
        jtxtFieldOrigin = new javax.swing.JTextField();
        tltOrigin = new javax.swing.JLabel();
        jtxtFieldDest = new javax.swing.JTextField();
        tltDest = new javax.swing.JLabel();
        jtxtFieldNumFl = new javax.swing.JTextField();
        tltNumFl = new javax.swing.JLabel();
        tlt = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Añadir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/icn back (1).png"))); // NOI18N
        btnBack.setContentAreaFilled(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        Añadir.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 80));

        btnAdd.setBackground(new java.awt.Color(204, 204, 204));
        btnAdd.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(51, 51, 51));
        btnAdd.setText("Añadir Vuelo");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        Añadir.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 510, 360, 40));

        jtxtFieldHrLleg.setBackground(new java.awt.Color(51, 51, 51));
        jtxtFieldHrLleg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtxtFieldHrLleg.setForeground(new java.awt.Color(204, 204, 204));
        jtxtFieldHrLleg.setBorder(null);
        jtxtFieldHrLleg.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtxtFieldHrLleg.setOpaque(true);
        jtxtFieldHrLleg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFieldHrLlegActionPerformed(evt);
            }
        });
        Añadir.add(jtxtFieldHrLleg, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 410, 30));

        tltHrLleg.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        tltHrLleg.setForeground(new java.awt.Color(255, 255, 255));
        tltHrLleg.setText("Hora Estimada de Llegada:");
        Añadir.add(tltHrLleg, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 410, 30));

        jtxtFieldHrParti.setBackground(new java.awt.Color(51, 51, 51));
        jtxtFieldHrParti.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtxtFieldHrParti.setForeground(new java.awt.Color(204, 204, 204));
        jtxtFieldHrParti.setBorder(null);
        jtxtFieldHrParti.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtxtFieldHrParti.setOpaque(true);
        jtxtFieldHrParti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFieldHrPartiActionPerformed(evt);
            }
        });
        Añadir.add(jtxtFieldHrParti, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 410, 30));

        tltHrParti.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        tltHrParti.setForeground(new java.awt.Color(255, 255, 255));
        tltHrParti.setText("Hora de Partida:");
        Añadir.add(tltHrParti, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 410, 30));

        jtxtFieldOrigin.setBackground(new java.awt.Color(51, 51, 51));
        jtxtFieldOrigin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtxtFieldOrigin.setForeground(new java.awt.Color(204, 204, 204));
        jtxtFieldOrigin.setBorder(null);
        jtxtFieldOrigin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtxtFieldOrigin.setOpaque(true);
        jtxtFieldOrigin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFieldOriginActionPerformed(evt);
            }
        });
        Añadir.add(jtxtFieldOrigin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 410, 30));

        tltOrigin.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        tltOrigin.setForeground(new java.awt.Color(255, 255, 255));
        tltOrigin.setText("Lugar de Origen:");
        Añadir.add(tltOrigin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 410, 30));

        jtxtFieldDest.setBackground(new java.awt.Color(51, 51, 51));
        jtxtFieldDest.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtxtFieldDest.setForeground(new java.awt.Color(204, 204, 204));
        jtxtFieldDest.setBorder(null);
        jtxtFieldDest.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtxtFieldDest.setOpaque(true);
        jtxtFieldDest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFieldDestActionPerformed(evt);
            }
        });
        Añadir.add(jtxtFieldDest, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 410, 30));

        tltDest.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        tltDest.setForeground(new java.awt.Color(255, 255, 255));
        tltDest.setText("Lugar de Destino:");
        Añadir.add(tltDest, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 410, 30));

        jtxtFieldNumFl.setBackground(new java.awt.Color(51, 51, 51));
        jtxtFieldNumFl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtxtFieldNumFl.setForeground(new java.awt.Color(204, 204, 204));
        jtxtFieldNumFl.setBorder(null);
        jtxtFieldNumFl.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtxtFieldNumFl.setOpaque(true);
        jtxtFieldNumFl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFieldNumFlActionPerformed(evt);
            }
        });
        Añadir.add(jtxtFieldNumFl, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 410, 30));

        tltNumFl.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        tltNumFl.setForeground(new java.awt.Color(255, 255, 255));
        tltNumFl.setText("Numero de Vuelo:");
        Añadir.add(tltNumFl, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 410, 30));

        tlt.setBackground(new java.awt.Color(204, 204, 204));
        tlt.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        tlt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tlt.setText("Añadir Vuelo");
        tlt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tlt.setOpaque(true);
        Añadir.add(tlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 100));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Background (1).jpg"))); // NOI18N
        Añadir.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1040, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 1031, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtFieldNumFlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFieldNumFlActionPerformed

    }//GEN-LAST:event_jtxtFieldNumFlActionPerformed

    private void jtxtFieldDestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFieldDestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFieldDestActionPerformed

    private void jtxtFieldOriginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFieldOriginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFieldOriginActionPerformed

    private void jtxtFieldHrPartiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFieldHrPartiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFieldHrPartiActionPerformed

    private void jtxtFieldHrLlegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFieldHrLlegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFieldHrLlegActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if(jtxtFieldNumFl.getText().trim().isEmpty() || jtxtFieldOrigin.getText().trim().isEmpty() || jtxtFieldDest.getText().trim().isEmpty() || jtxtFieldHrParti.getText().trim().isEmpty() || jtxtFieldHrLleg.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Porfavor rellene todas las casillas con la informacion solicitada para poder continuar", "Complete las casillas", JOptionPane.INFORMATION_MESSAGE);
        }else{
            String numFl = jtxtFieldNumFl.getText();
            String origin = jtxtFieldOrigin.getText() ;
            String desti =  jtxtFieldDest.getText();
            String hrParti =  jtxtFieldHrParti.getText();
            String hrLleg = jtxtFieldHrLleg.getText();
            Vuelo vuelo = new Vuelo(numFl, origin, desti, hrParti, hrLleg);
            sis.addVuelo(vuelo);
            JOptionPane.showMessageDialog(null, "El vuelo ha sido añadido correctamente", "Vuelo añadido", JOptionPane.INFORMATION_MESSAGE);
            jtxtFieldNumFl.setText("");
            jtxtFieldOrigin.setText("");
            jtxtFieldDest.setText("");
            jtxtFieldHrParti.setText("");
            jtxtFieldHrLleg.setText("");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Principal princi = new Principal(sis);
        princi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Añadir;
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JTextField jtxtFieldDest;
    private javax.swing.JTextField jtxtFieldHrLleg;
    private javax.swing.JTextField jtxtFieldHrParti;
    private javax.swing.JTextField jtxtFieldNumFl;
    private javax.swing.JTextField jtxtFieldOrigin;
    private javax.swing.JLabel tlt;
    private javax.swing.JLabel tltDest;
    private javax.swing.JLabel tltHrLleg;
    private javax.swing.JLabel tltHrParti;
    private javax.swing.JLabel tltNumFl;
    private javax.swing.JLabel tltOrigin;
    // End of variables declaration//GEN-END:variables
}
