package IGU;

import Logica.Sistema;
import Logica.Vuelo;
import java.util.LinkedList;
import java.util.Queue;
import javax.swing.DefaultListModel;

public class Espera extends javax.swing.JFrame {
    private Sistema sis;
    public Espera(Sistema sistema) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        sis = sistema;
        mostrarEspera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Espera = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        jlistEspera = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>();
        tlt = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Espera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/icn back (1).png"))); // NOI18N
        btnBack.setContentAreaFilled(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        Espera.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 80));

        jList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlistEspera.setViewportView(jList);

        Espera.add(jlistEspera, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 600, 380));

        tlt.setBackground(new java.awt.Color(204, 204, 204));
        tlt.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        tlt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tlt.setText("Lista de Vuelos en Espera");
        tlt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tlt.setOpaque(true);
        Espera.add(tlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 100));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Background (1).jpg"))); // NOI18N
        Espera.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1040, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Espera, javax.swing.GroupLayout.PREFERRED_SIZE, 1031, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Espera, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mostrarEspera() {
        DefaultListModel<String> model = new DefaultListModel<>();
        Queue<Vuelo> espera = sis.getColaEspera();
        for (Vuelo vuelo : espera) {
            model.addElement(vuelo.toString()); 
        }
        jList.setModel(model);
    }
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Principal princi = new Principal(sis);
        princi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Espera;
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnBack;
    private javax.swing.JList<String> jList;
    private javax.swing.JScrollPane jlistEspera;
    private javax.swing.JLabel tlt;
    // End of variables declaration//GEN-END:variables
}
