package IGU;

import Logica.Sistema;
import Logica.Vuelo;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class Lista extends javax.swing.JFrame {
    private Sistema sis;
    
    public Lista(Sistema sistema) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        this.sis = sistema;
        mostrarVuelos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jlistVuelos = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>();
        btnBack = new javax.swing.JButton();
        tltNumFl = new javax.swing.JLabel();
        tlt = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListMouseClicked(evt);
            }
        });
        jlistVuelos.setViewportView(jList);

        Panel.add(jlistVuelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 600, 380));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/icn back (1).png"))); // NOI18N
        btnBack.setContentAreaFilled(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        Panel.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 80));

        tltNumFl.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        tltNumFl.setForeground(new java.awt.Color(255, 255, 255));
        tltNumFl.setText("Seleccione el vuelo que quiera autorizar");
        Panel.add(tltNumFl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 460, 30));

        tlt.setBackground(new java.awt.Color(204, 204, 204));
        tlt.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        tlt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tlt.setText("Lista de Vuelos");
        tlt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tlt.setOpaque(true);
        Panel.add(tlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 100));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Background (1).jpg"))); // NOI18N
        Panel.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1040, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1031, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mostrarVuelos() {
        DefaultListModel<String> model = new DefaultListModel<>();
        LinkedList<Vuelo> vuelos = sis.getListaVuelos();
        for (Vuelo vuelo : vuelos) {
            model.addElement(vuelo.toString()); 
        }
        jList.setModel(model);
    }

    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Principal princi = new Principal(sis);
        princi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void jListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListMouseClicked
        if (evt.getClickCount() == 2) {
            int selectedIndex = jList.getSelectedIndex();
            if (selectedIndex != -1) {
                Vuelo vuelo = sis.getListaVuelos().get(selectedIndex);
                sis.autorizarVuelo(vuelo);
                JOptionPane.showMessageDialog(null, "La salida del vuelo ha sido autorizada correctamente", "Vuelo Autorizado", JOptionPane.INFORMATION_MESSAGE);
                mostrarVuelos();
            }
        }
    }//GEN-LAST:event_jListMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnBack;
    private javax.swing.JList<String> jList;
    private javax.swing.JScrollPane jlistVuelos;
    private javax.swing.JLabel tlt;
    private javax.swing.JLabel tltNumFl;
    // End of variables declaration//GEN-END:variables
}
