package IGU;

import Logica.Sistema;

public class Principal extends javax.swing.JFrame {
    private Sistema sis;
    public Principal(Sistema sistema) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        sis = sistema;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        imgHist = new javax.swing.JLabel();
        txtHist = new javax.swing.JLabel();
        bgBtnHist = new javax.swing.JLabel();
        btnHist = new javax.swing.JButton();
        imgWait = new javax.swing.JLabel();
        txtWait = new javax.swing.JLabel();
        bgBtnWait = new javax.swing.JLabel();
        btnWait = new javax.swing.JButton();
        imgList = new javax.swing.JLabel();
        txtList = new javax.swing.JLabel();
        bgBtnList = new javax.swing.JLabel();
        btnList = new javax.swing.JButton();
        imgRem = new javax.swing.JLabel();
        txtRem = new javax.swing.JLabel();
        bgBtnRem = new javax.swing.JLabel();
        btnRem = new javax.swing.JButton();
        imgAdd = new javax.swing.JLabel();
        txtAdd = new javax.swing.JLabel();
        bgBtnAdd = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        tlt = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1030, 580));

        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgHist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/icn historial (1).png"))); // NOI18N
        Panel.add(imgHist, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 160, 110));

        txtHist.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        txtHist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHist.setText("Historial");
        txtHist.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Panel.add(txtHist, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 180, 50));

        bgBtnHist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/bg btn (1).png"))); // NOI18N
        bgBtnHist.setText("jLabel1");
        Panel.add(bgBtnHist, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 200, 170));

        btnHist.setBackground(new java.awt.Color(204, 204, 204));
        btnHist.setContentAreaFilled(false);
        btnHist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistActionPerformed(evt);
            }
        });
        Panel.add(btnHist, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 200, 170));

        imgWait.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/icn espera (1).png"))); // NOI18N
        Panel.add(imgWait, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 160, 110));

        txtWait.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        txtWait.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtWait.setText("Lista de Espera");
        txtWait.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Panel.add(txtWait, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 180, 50));

        bgBtnWait.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/bg btn (1).png"))); // NOI18N
        bgBtnWait.setText("jLabel1");
        Panel.add(bgBtnWait, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 200, 170));

        btnWait.setBackground(new java.awt.Color(204, 204, 204));
        btnWait.setContentAreaFilled(false);
        btnWait.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWaitActionPerformed(evt);
            }
        });
        Panel.add(btnWait, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 200, 170));

        imgList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/icn lista (1).png"))); // NOI18N
        Panel.add(imgList, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, 160, 110));

        txtList.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        txtList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtList.setText("Lista de Vuelos");
        txtList.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Panel.add(txtList, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, 180, 50));

        bgBtnList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/bg btn (1).png"))); // NOI18N
        bgBtnList.setText("jLabel1");
        Panel.add(bgBtnList, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, 200, 170));

        btnList.setBackground(new java.awt.Color(204, 204, 204));
        btnList.setContentAreaFilled(false);
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });
        Panel.add(btnList, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, 200, 170));

        imgRem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/icn avion (2).png"))); // NOI18N
        Panel.add(imgRem, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 160, 110));

        txtRem.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        txtRem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRem.setText("Cancelar Vuelo");
        txtRem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Panel.add(txtRem, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 180, 50));

        bgBtnRem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/bg btn (1).png"))); // NOI18N
        bgBtnRem.setText("jLabel1");
        Panel.add(bgBtnRem, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 200, 170));

        btnRem.setBackground(new java.awt.Color(204, 204, 204));
        btnRem.setContentAreaFilled(false);
        btnRem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemActionPerformed(evt);
            }
        });
        Panel.add(btnRem, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 200, 170));

        imgAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/icn avion (1).png"))); // NOI18N
        Panel.add(imgAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 160, 110));

        txtAdd.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        txtAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAdd.setText("Añadir Vuelo");
        txtAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Panel.add(txtAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 180, 50));

        bgBtnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/bg btn (1).png"))); // NOI18N
        bgBtnAdd.setText("jLabel1");
        Panel.add(bgBtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 200, 170));

        btnAdd.setBackground(new java.awt.Color(204, 204, 204));
        btnAdd.setContentAreaFilled(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        Panel.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 200, 170));

        tlt.setBackground(new java.awt.Color(204, 204, 204));
        tlt.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        tlt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tlt.setText("AviaTicket");
        tlt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tlt.setOpaque(true);
        Panel.add(tlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 100));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Background (1).jpg"))); // NOI18N
        Panel.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1030, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1031, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 146, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        Añadir add = new Añadir(sis);
        add.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
        Lista list = new Lista(sis);
        list.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListActionPerformed

    private void btnRemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemActionPerformed
        Remover rem = new Remover(sis);
        rem.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRemActionPerformed

    private void btnWaitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWaitActionPerformed
        Espera wait = new Espera(sis);
        wait.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnWaitActionPerformed

    private void btnHistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistActionPerformed
        Historial hist = new Historial(sis);
        hist.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHistActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bgBtnAdd;
    private javax.swing.JLabel bgBtnHist;
    private javax.swing.JLabel bgBtnList;
    private javax.swing.JLabel bgBtnRem;
    private javax.swing.JLabel bgBtnWait;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnHist;
    private javax.swing.JButton btnList;
    private javax.swing.JButton btnRem;
    private javax.swing.JButton btnWait;
    private javax.swing.JLabel imgAdd;
    private javax.swing.JLabel imgHist;
    private javax.swing.JLabel imgList;
    private javax.swing.JLabel imgRem;
    private javax.swing.JLabel imgWait;
    private javax.swing.JLabel tlt;
    private javax.swing.JLabel txtAdd;
    private javax.swing.JLabel txtHist;
    private javax.swing.JLabel txtList;
    private javax.swing.JLabel txtRem;
    private javax.swing.JLabel txtWait;
    // End of variables declaration//GEN-END:variables
}
