package IGU;

import Logica.Sistema;
import Logica.Vuelo;
import javax.swing.JOptionPane;

public class Remover extends javax.swing.JFrame {
    private Sistema sis;
    String numFl;
    Vuelo vuelo;
    public Remover(Sistema sistema) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Añadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        sis = sistema;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Remover = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnRem = new javax.swing.JButton();
        jtxtFieldInfo = new javax.swing.JTextField();
        tltInfo = new javax.swing.JLabel();
        jtxtFieldNumFl = new javax.swing.JTextField();
        tltNumFl = new javax.swing.JLabel();
        tlt = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Remover.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/icn back (1).png"))); // NOI18N
        btnBack.setContentAreaFilled(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        Remover.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 80));

        btnSearch.setBackground(new java.awt.Color(204, 204, 204));
        btnSearch.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(51, 51, 51));
        btnSearch.setText("Buscar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        Remover.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 180, 40));

        btnRem.setBackground(new java.awt.Color(204, 204, 204));
        btnRem.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        btnRem.setForeground(new java.awt.Color(51, 51, 51));
        btnRem.setText("Cancelar Vuelo");
        btnRem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemActionPerformed(evt);
            }
        });
        Remover.add(btnRem, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 360, 40));

        jtxtFieldInfo.setBackground(new java.awt.Color(51, 51, 51));
        jtxtFieldInfo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtxtFieldInfo.setForeground(new java.awt.Color(204, 204, 204));
        jtxtFieldInfo.setBorder(null);
        jtxtFieldInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtxtFieldInfo.setOpaque(true);
        jtxtFieldInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFieldInfoActionPerformed(evt);
            }
        });
        Remover.add(jtxtFieldInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 800, 30));

        tltInfo.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        tltInfo.setForeground(new java.awt.Color(255, 255, 255));
        tltInfo.setText("Informacion Completa del Vuelo:");
        Remover.add(tltInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 410, 30));

        jtxtFieldNumFl.setBackground(new java.awt.Color(51, 51, 51));
        jtxtFieldNumFl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtxtFieldNumFl.setForeground(new java.awt.Color(204, 204, 204));
        jtxtFieldNumFl.setBorder(null);
        jtxtFieldNumFl.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtxtFieldNumFl.setOpaque(true);
        jtxtFieldNumFl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFieldNumFlActionPerformed(evt);
            }
        });
        Remover.add(jtxtFieldNumFl, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 410, 30));

        tltNumFl.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        tltNumFl.setForeground(new java.awt.Color(255, 255, 255));
        tltNumFl.setText("Numero de Vuelo:");
        Remover.add(tltNumFl, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 410, 30));

        tlt.setBackground(new java.awt.Color(204, 204, 204));
        tlt.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        tlt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tlt.setText("Cancelar Vuelo");
        tlt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tlt.setOpaque(true);
        Remover.add(tlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 100));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Background (1).jpg"))); // NOI18N
        Remover.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1040, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Remover, javax.swing.GroupLayout.PREFERRED_SIZE, 1031, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Remover, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Principal princi = new Principal(sis);
        princi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemActionPerformed
        sis.removeFlight(vuelo);
        JOptionPane.showMessageDialog(null, "El vuelo ha sido cancelado correctamente", "Vuelo Cancelado", JOptionPane.INFORMATION_MESSAGE);
        jtxtFieldInfo.setText("");
        jtxtFieldNumFl.setText("");
    }//GEN-LAST:event_btnRemActionPerformed

    private void jtxtFieldNumFlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFieldNumFlActionPerformed

    }//GEN-LAST:event_jtxtFieldNumFlActionPerformed

    private void jtxtFieldInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFieldInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFieldInfoActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        numFl = jtxtFieldNumFl.getText();
        vuelo = sis.buscarVuelo(numFl);
        if(jtxtFieldNumFl.getText().trim().isEmpty())
            JOptionPane.showMessageDialog(null, "Porfavor rellene la casilla con la informacion solicitada para poder continuar", "Complete las casillas", JOptionPane.INFORMATION_MESSAGE);
        else{
            if(sis.buscarVuelo(numFl) != null){
                jtxtFieldInfo.setText(vuelo.toString());
            }
            else{
                jtxtFieldInfo.setText("Vuelo no Encontrado");
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Remover;
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRem;
    private javax.swing.JButton btnSearch;
    private javax.swing.JTextField jtxtFieldInfo;
    private javax.swing.JTextField jtxtFieldNumFl;
    private javax.swing.JLabel tlt;
    private javax.swing.JLabel tltInfo;
    private javax.swing.JLabel tltNumFl;
    // End of variables declaration//GEN-END:variables
}
